logging:
  file.name: ./log/backend.log
  level:
    root: INFO
    org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping: TRACE
  pattern:
    level: r=%X{r} ip=%X{ip} u=%X{u} %5p

spring:
  datasource:
    url: jdbc:h2:file:./database/db;AUTO_SERVER=TRUE;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: admin
    password: password
  jpa:
    # Set this property to true if you want to see the executed queries
    show-sql: false
    hibernate:
      ddl-auto: update
    # Allows to fetch lazy properties outside of the original transaction. Although this sounds helpful, the property
    # is disabled since it breaks the principle of least astonishment and leads to bad performance. To learn more,
    # follow this link: https://bit.ly/2LaX9ku
    open-in-view: false
  mail:
    host: smtp.freesmtpservers.com
    port: 25
    username:
    password:
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false
            required: false
  data:
    web:
      sort:
        sort-parameter: "b7379500-2eaf-4985-bb30-5fd1638278b8"
      pageable:
        default-page-size: 20
        max-page-size: 20

security:
  auth:
    header: Authorization
    prefix: "Bearer "
    login-uri: /api/v1/authentication
  jwt:
    secret: ?E(H+MbQeThWmZq4t7w!z%C*F-J@NcRfUjXn2r5u8x/A?D(G+KbPdSgVkYp3s6v9
    type: JWT
    issuer: secure-backend
    audience: secure-app
    # 12 hours in milliseconds
    expiration-time: 43200000
    # 1 hour in milliseconds
    password-reset-expiration-time: 3600000

files:
  public-serve-url: /public-files/**
  public-disk-path: ./public-files/
  embedded-serve-url: /private-files/**

pdf:
  templates:
    path: pdf/templates/
    invoice: invoice.ftlh

management:
  server:
    port: 8081
  endpoint:
    shutdown:
      enabled: true
    metrics:
      enabled: true
    prometheus:
      enabled: true
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - shutdown
          - metrics
          - env
  prometheus:
    metrics:
      export:
        enabled: true

---
spring:
  config:
    activate:
      on-cloud-platform: kubernetes
  lifecycle:
    timeout-per-shutdown-phase: 30s
server:
  shutdown: graceful
